[project]
name = "the_office"
version = "0.1.0"
description = "Collection of episodes of The Office."
authors = [
    {name = "Artem Ermulin", email = "artem.ermulin@ya.ru"},
]
dependencies = [
    "pydantic>=2.4.2",
    "bs4>=0.0.2",
    "pandas>=1.1.5",
    "requests>=2.31.0",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
